import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/context/auth-provider";
import { ThemeProvider } from "@/context/theme-provider";
// import { SocketProvider } from "@/context/socket-provider";
import { QueryProvider } from "@/context/query-provider";
import { SocketProvider } from "@/context/socket-provider";
import { ReduxProvider } from "@/context/redux-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="red" showSpinner={false} speed={200} />
        <ReduxProvider>
          <AuthProvider>
            <QueryProvider>
              <SocketProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
                >
                  {children}
                  <Toaster />
                </ThemeProvider>
              </SocketProvider>
            </QueryProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
